### ISSUE TITLE
DispatchHttpCall-dispatch httpcall failed: error status returned by host: bad argument 

### ISSUE THREAD

**Issue by mohanchoudary** [tetratelabs/proxy-wasm-go-sdk#199]
I am getting the following error when trying to use DispatchHttpCall.
```go
	hs := [][2]string{
		{":method", "GET"}, {":authority", "some_authority"}, {":path", "/"}, {"accept", "*/*"},
	}

	if _, err := proxywasm.DispatchHttpCall("mirror", hs, originalBody, nil,
		5000, callback); err != nil {
		proxywasm.LogCriticalf("dispatch httpcall failed : %v", err)
	}
```

envoy.yaml
```
static_resources:
  listeners:
    - name: main
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 18000
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: web_service
                http_filters:
                  - name: envoy.filters.http.wasm
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          vm_config:
                            runtime: "envoy.wasm.runtime.v8"
                            code:
                              local:
                                filename: "./examples/dispatch_call_on_tick/main.go.wasm"
                  - name: envoy.filters.http.router

    - name: staticreply
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8099
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "example body\n"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config: {}
  clusters:
   - name: mirror
     connect_timeout: 10s
     type: STRICT_DNS
     lb_policy: ROUND_ROBIN
     load_assignment:
       cluster_name: mirror
       endpoints:
       - lb_endpoints:
         - endpoint:
             address:
               socket_address:
                 address: gorrpass-service.default.svc.cluster.local
                 port_value: 8080
   - name: gloo.gloo-system.svc.cluster.local:9977
     connect_timeout: 10s
     type: STRICT_DNS
     lb_policy: ROUND_ROBIN
     load_assignment:
       cluster_name: gloo.gloo-system.svc.cluster.local:9977
       endpoints:
       - lb_endpoints:
         - endpoint:
             address:
               socket_address:
                 address: gloo.gloo-system.svc.cluster.local
                 port_value: 9977 

admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 19000
```
