### ISSUE TITLE
the hostcall of 'SetProperty' didn't work

### ISSUE THREAD

**Issue by FeiYing9** [tetratelabs/proxy-wasm-go-sdk#207]
## Describe the bug / error
I have created a `TcpContext` for tcp stream, and I have codes like this:
```go
func (ctx *networkContext) OnNewConnection() types.Action {
  // get and print the property of  "destination.address"
  addr, err := proxywasm.GetProperty([]string{"destination", "address"})
  ......
  proxywasm.LogInfof("destination address: %s", string(addr))
  ......
  // modify this property, and it's not return an error
  addr := "10.109.244.108:8080"             
  err = proxywasm.SetProperty([]string{"destination", "address"}, []byte(addr))
  ......
  proxywasm.LogInfof(">>>>>> set property of '%s' to '%s'", "destination.address", addr)
  ......
   // get and print again
   addr, err = proxywasm.GetProperty([]string{"destination", "address"})
  ......
  proxywasm.LogInfof("destination address: %s", string(addr))
  ......
}
```
the property value printed seconed time is the same as it's first print, so the hostcall of 'SetProperty' didn't work

the istio-proxy log:
```bash
[root@linux164 ~]# kubectl -nwasm logs -f deploy/sleep -c istio-proxy --tail 50
......
2021-08-17T01:16:36.961022Z	info	envoy wasm	wasm log: >>>>>>>> on new connection (plugin1)
......
2021-08-17T01:16:36.961096Z	info	envoy wasm	wasm log: destination address: 10.107.169.228:9091
......
2021-08-17T01:16:36.961152Z	info	envoy wasm	wasm log: >>>>>> set property of 'destination.address' to '10.109.244.108:8080'
......
2021-08-17T01:16:36.961201Z	info	envoy wasm	wasm log: destination address: 10.107.169.228:9091
......
2021-08-17T01:16:36.963290Z	info	envoy wasm	wasm log: >>>>>> downstream data received (plugin1) >>>>>>
GET /healthz HTTP/1.1
Host: goserver:9091
User-Agent: curl/7.76.1-DEV
Accept: */*


2021-08-17T01:16:36.965160Z	info	envoy wasm	wasm log: >>>>>> uptream data received (plugin1) >>>>>>
HTTP/1.1 200 OK
Date: Tue, 17 Aug 2021 01:16:36 GMT
Content-Length: 58
Content-Type: text/plain; charset=utf-8

{"status":"healthy","hostName":"goserver-7c5cc7cf6-sjmnv"}
2021-08-17T01:16:36.965969Z	info	envoy wasm	wasm log: >>>>>> downstream (plugin1) datasize is 0.
2021-08-17T01:16:36.966902Z	info	envoy wasm	wasm log: >>>>>> upstream (plugin1) datasize is 0.
2021-08-17T01:16:36.967186Z	info	envoy wasm	wasm log: OnUpstreamClose (plugin1)! peerType is 0.
2021-08-17T01:16:36.967959Z	info	envoy wasm	wasm log: downstream connection close (plugin1)!
2021-08-17T01:16:36.968353Z	info	envoy wasm	wasm log: >>>>>>>> on stream down (plugin1)
```

that's right that I send a http traffic for test, I just want to modify it's destination address (customize upstream selection)

## What is your Envoy/Istio version?
```bash
[root@linux164 ~]# istioctl version
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (24 proxies)

istio-proxy@sleep-7b8548cbb-qd47z:/$ envoy --version
envoy  version: 9ede4aa9d31f9853ef9e61beb69ea9864854e268/1.17.1/Clean/RELEASE/BoringSSL
```
## What is the SDK version?
`github.com/tetratelabs/proxy-wasm-go-sdk v0.14.0`

## What is your TinyGo version?
it's build in a docker environment:
```bash
root@tinygo-79dc5b4869-swsl7:/# tinygo version
tinygo version 0.19.0 linux/amd64 (using go version go1.16.5 and LLVM version 11.0.0)

root@tinygo-79dc5b4869-swsl7:/# go version
go version go1.16.5 linux/amd64

root@tinygo-79dc5b4869-swsl7:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

I build the docker image myself just like this:
```
FROM ubuntu-base:18.04

ENV PATH /usr/local/go/bin:$PATH
ENV GOPATH /opt/code
ENV GOPROXY https://goproxy.cn,https://goproxy.io,direct
ENV GO111MODULE on

COPY * /home/

RUN cd /home && \
    mv /home/sources.list /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y curl vim inetutils-ping jq wget gcc && \
    # tinygo
    dpkg -i tinygo_0.19.0_amd64.deb && \
    # golang
    tar -C /usr/local -zxvf  go1.16.5.linux-amd64.tar.gz && \
    rm -rf /home/*
```

build command:
```bash
tinygo build -o build/socket.wasm -target=wasi -wasm-abi=generic .
```
## URL or snippet of your code including Envoy configuration
the envoyfilter:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: sleep-outbound-goserver-9091-socket-wasm
  namespace: wasm
spec:
  workloadSelector:
    labels:
      app: sleep
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          name: 10.107.169.228_9091     # (goserver.wasm.svc) clusterIP_svcPort
          filterChain:
            filter:
              name: envoy.filters.network.tcp_proxy 
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.network.wasm
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
            config:
              name: my-filter
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: "plugin1"
              vm_config:
                vm_id: "same_vm_id"
                runtime: "envoy.wasm.runtime.v8"
                configuration:
                  '@type': type.googleapis.com/google.protobuf.StringValue
                  value: "socket vm"
                code:
                  local:
                    filename: "/home/host/wasm/build/socket.wasm"
```

yes, I mount the `socket.wasm` into the deploy of `sleep`
