### ISSUE TITLE
grpc status is always -1

### ISSUE THREAD

**Issue by robodenitro** [tetratelabs/proxy-wasm-go-sdk#209]
PLEASE FILL IN THE FOLLOWINGS for EVERY ISSUE you make.

## Describe the bug / error
We use proxy-wasm-go-sdk to implement http envoy filter which rejects or passes a request based on headers . Both client and server are grpc. With usage of [SendHttpResponse ](https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/eeb70ed00efa732bbde07a69df83b6a147417627/proxywasm/hostcall.go#L480) we always get status -1 (or 4294967295 since it is uint32)

Client can't handle this properly:
```
transport: malformed grpc-status: strconv.ParseInt: parsing "4294967295": value out of range
```
Envoy logs:
```
'content-type', 'application/grpc'
'grpc-status', '4294967295'
'grpc-message', 'Please include custom-header.'
'date', 'Wed, 18 Aug 2021 07:21:14 GMT'
'server', 'envoy'
```
## What is your Envoy/Istio version?
1.19.0

## What is the SDK version?
v0.14.1-0.20210817114515-eeb70ed00efa

## What is your TinyGo version?
tinygo version 0.19.0 darwin/amd64 (using go version go1.16.4 and LLVM version 11.0.0)

## URL or snippet of your code including Envoy configuration
envoy http filters
```
                http_filters:
                  - name: envoy.filters.http.wasm
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          vm_config:
                            runtime: "envoy.wasm.runtime.v8"
                            code:
                              local:
                                filename: "./hello.wasm"  
```

part of go code:
```
func (ctx *httpHeaders) OnHttpRequestHeaders(numHeaders int, endOfStream bool) types.Action {
...
    _, err = proxywasm.GetHttpRequestHeader("custom-header")
    if err != nil {
	respHeaders := [][2]string{}
	proxywasm.SendHttpResponse(400, respHeaders, []byte(`Please include custom-header.`))
	return types.ActionPause
    }
...
}
```
