### ISSUE TITLE
Clarification about VM sharing between a singleton and other (http/network) filters

### ISSUE THREAD

**Issue by ratnadeepb** [tetratelabs/proxy-wasm-go-sdk#296]
## Describe the bug / error
The [Wasm Service](https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/doc/OVERVIEW.md#wasm-service) section mentions that 
```
The top singleton field is normally set true. In this way, only one VM for this configuration exists across all the threads of Envoy process, and runs on the Envoy's main thread so that it won't block any worker threads.
```
Does this mean that all threads - main and workers - have access to this VM?

If that is not the case, then the [sharing VM](https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/doc/OVERVIEW.md#sharing-one-vm-among-multiple-plugins-per-thread) section confuses me since I can use the same `vm_id` for both a singleton and http filters.

## What is your Envoy/Istio version?
1.22 (I am using `func-e`)

## What is the SDK version?
I am not using the Go SDK (Rust) but I doubt that matters in this regard.

## What is your TinyGo version?
NA

## URL or snippet of your code including Envoy configuration
```YAML
# the singleton service (Wasm Service)
bootstrap_extensions:
- name: envoy.bootstrap.wasm
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.wasm.v3.WasmService
    singleton: true
    config:
      name: "singleton"
      root_id: "singleton"
      vm_config:
        runtime: "envoy.wasm.runtime.v8"
        vm_id: "1"
        code:
          local:
            filename: "/etc/singleton.wasm"
        allow_precompiled: true
```
and the filters:
```YAML
http_filters:
- name: envoy.filters.http.wasm
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
    config:
      name: "http"
      root_id: "http
      vm_config:
        runtime: "envoy.wasm.runtime.v8"
        vm_id: "1"
        code:
          local:
            filename: "/etc/http.wasm"
         allow_precompiled: true
- name: envoy.filters.http.router
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
