### ISSUE TITLE
X-Forwarded-For Headers for DispatchHttpCall

### ISSUE THREAD

**Issue by cgrotz** [tetratelabs/proxy-wasm-go-sdk#300]
## Describe the bug / error
I'm using `DispatchHttpCall` to retrieve some metadata from the GCP Metadata server to enrich on the original request envoy is proxying. For some reason, the HTTP request gets a `X-Forwarded-For` header appended to the request. The problem is, that the GCP Metadata server responds with a 403 should a X-Forwarded-For header be present. 

I tried adding `use_remote_address: false` and `skip_xff_append: true` to the `HttpConnectionManager` config but it didn't change. Funny enough the reverse proxy with Httpbin in my example doesn't add the `X-Forwarded-For` header at all. (remember to add ?show_env=1 otherwise it will not show up)

I don't think this is a problem of proxy-wasm-go-sdk but the underlying implementation of `DispatchHttpCall`, it would be great if you could point me to the correct party so I can raise this topic there.

## What is your Envoy/Istio version?
envoy v1.20.6

## What is the SDK version?
v0.18.0

## What is your TinyGo version?
0.24.0

## URL or snippet of your code including Envoy configuration
```go
package main

import (
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm"
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
	"fmt"
)
const tickMilliseconds uint32 = 15000

var authHeader string

func main() {
	proxywasm.SetVMContext(&vmContext{})
}

type vmContext struct {
	// Embed the default VM context here,
	// so that we don't need to reimplement all the methods.
	types.DefaultVMContext
}

// Override types.DefaultVMContext.
func (*vmContext) NewPluginContext(contextID uint32) types.PluginContext {
	return &pluginContext{contextID: contextID}
}

type pluginContext struct {
	// Embed the default plugin context here,
	// so that we don't need to reimplement all the methods.
	types.DefaultPluginContext
	contextID uint32
	callBack  func(numHeaders, bodySize, numTrailers int)
}

// Override types.DefaultPluginContext.
func (*pluginContext) NewHttpContext(contextID uint32) types.HttpContext {
	return &httpAuthRandom{contextID: contextID}
}

type httpAuthRandom struct {
	// Embed the default http context here,
	// so that we don't need to reimplement all the methods.
	types.DefaultHttpContext
	contextID uint32
}

// Override types.DefaultPluginContext.
func (ctx *pluginContext) OnPluginStart(pluginConfigurationSize int) types.OnPluginStartStatus {
	if err := proxywasm.SetTickPeriodMilliSeconds(tickMilliseconds); err != nil {
		proxywasm.LogCriticalf("failed to set tick period: %v", err)
		return types.OnPluginStartStatusFailed
	}
	proxywasm.LogInfof("set tick period milliseconds: %d", tickMilliseconds)
	ctx.callBack = func(numHeaders, bodySize, numTrailers int) {
	
		headers,_ := proxywasm.GetHttpCallResponseHeaders()
		for _, s := range headers {
			proxywasm.LogInfof("Resp Header %v:", s[0], s[1])
		}
		body, _ := proxywasm.GetHttpCallResponseBody(0,2048)
		authHeader = string(body)
		proxywasm.LogInfof("gotAuthToken: %v", authHeader)
	}
	ctx.OnTick()
	return types.OnPluginStartStatusOK
}

func (ctx *httpAuthRandom) OnHttpRequestHeaders(int, bool) types.Action {
	proxywasm.AddHttpRequestHeader("Authorization", fmt.Sprintf("Bearer %s",authHeader))

	return types.ActionContinue
}

// Override types.DefaultPluginContext.
func (ctx *pluginContext) OnTick() {
	path := fmt.Sprintf("/computeMetadata/v1/instance/name")
	hs := [][2]string{
		{":method", "GET"},{":path", path}, {":authority", "169.254.169.254"},{"Host", "169.254.169.254"},{"Metadata-Flavor", "Google"},{"Accept", "*/*"}, // {":authority", "169.254.169.254"}, 
	}
	if _, err := proxywasm.DispatchHttpCall("gcp_metadata_server", hs, nil, nil, 5000, ctx.callBack); err != nil {
		proxywasm.LogCriticalf("dispatch httpcall failed: %v", err)
	}
}
```
envoy
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 8001
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 8085
    filter_chains:
      - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              route_config:
                name: local_route
                virtual_hosts:
                  - name: local_service
                    domains: ["*"]
                    routes:
                      - match: { prefix: "/" }
                        route: { cluster: svc_hello }
              http_filters:
                - name: envoy.filters.http.wasm
                  typed_config:
                    "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                    type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                    value:
                      config:
                        name: "my_plugin"
                        root_id: "my_root_id"
                        vm_config:
                          vm_id: "my_vm_id"
                          runtime: "envoy.wasm.runtime.v8"
                          code:
                            local:
                              filename: "/etc/envoy/hello.wasm"
                          allow_precompiled: true
                - name: envoy.filters.http.router
                  typed_config: {}

  clusters:
    - name: svc_hello
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: svc_hello
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: httpbin.org
                      port_value: 80
    - name: gcp_metadata_server
      connect_timeout: 5000s
      type: STATIC
      lb_policy: round_robin
      load_assignment:
        cluster_name: gcp_metadata_server
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 169.254.169.254
                      port_value: 80
```
