### ISSUE TITLE
Get environment variable from Istio WasmPlugin

### ISSUE THREAD

**Issue by jallaix** [tetratelabs/proxy-wasm-go-sdk#342]
Here is my current WasmPlugin manifest definition:
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: front-proxy-checker
  namespace: ingress-istio
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://my_registry/my_image:v0
  phase: AUTHN
  vmConfig:
    env:
    - name: FRONT_PROXY_SECRET
      value: A_SECRET_VALUE
```

I tried some commands like `os.Getenv("FRONT_PROXY_SECRET")` or `proxywasm.GetVMConfiguration()` but none of them allow to retrieve the value of the environment variable.

Is there a solution to this problem ?
