### ISSUE TITLE
 bad argument on proxywasm.DispatchHttpCall. 

### ISSUE THREAD

**Issue by ajohnstone** [tetratelabs/proxy-wasm-go-sdk#345]
## Describe the bug / error
bad argument on proxywasm.DispatchHttpCall.
When executing similar in rust the call succeeds.

```
istio-ingressgateway-5c99bfd6c-sg99z istio-proxy 2022-11-17T23:05:49.364677Z	
critical	envoy wasm	wasm log: dispatch httpcall failed: error status returned by host: bad argument outbound|80||test.default.svc.cluster.local
```

## What is your Envoy/Istio version?
1.15.1

## What is the SDK version?
github.com/tetratelabs/proxy-wasm-go-sdk v0.20.0

## What is your TinyGo version?
tinygo version 0.26.0 darwin/amd64 (using go version go1.19.2 and LLVM version 14.0.0)

## URL or snippet of your code including Envoy configuration

```
func (ctx *pluginContext) OnTick() {
	headers := [][2]string{
		{":method", "GET"},
		{":authority","test.default.svc.cluster.local"},
		{"accept", "*/*"},
	}

	outbound := "outbound|80||test.default.svc.cluster.local"
	//outbound := "test.default.svc.cluster.local:80"
	//outbound := "outbound|9898||test.default.svc.cluster.local"
	if _, err := proxywasm.DispatchHttpCall(outbound, headers, nil, nil, 5000, ctx.callBack); err != nil {
		proxywasm.LogCriticalf("dispatch httpcall failed: %v %s", err, outbound)
	}
}
```
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata
  name: global
  namespace: default
spec:
  gateways:
  - istio-system/global-gateway
  hosts:
  - test.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: test.default.svc.cluster.local
        port:
          number: 80
```

```
istioctl proxy-config cluster --file ./config_dump  --fqdn test.default.svc.cluster.local
SERVICE FQDN                           PORT     SUBSET     DIRECTION     TYPE     DESTINATION RULE
test.default.svc.cluster.local     80       -          outbound      EDS
```
