### ISSUE TITLE
Is it possible to make HTTPS calls using DipatchHttpCall 

### ISSUE THREAD

**Issue by harsha-konda** [tetratelabs/proxy-wasm-go-sdk#416]
## Describe the bug / error
Is HTTPS protocol supported by DispatchHttpCall? I looked around in the docs and there was nothing to indicated explicitly that https is supported.
here's my code to make a https call

```
proxywasm.DispatchHttpCall(
		"outbound|443||echoservice.com",
	{{":authority" ,"echoservice.com" }, {":scheme","https"}, {":method","GET"}},
		nil, nil, 5000,
		ctx.dispatchCallback,
	)

```
I got the following error

```
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
</body>
</html>
```

## What is your Envoy/Istio version?
1.2.0
## What is your TinyGo version?
0.30.0

**Comment by harsha-konda** [comment]
Since no one has answered this , here's a workaround that i found 

The request in the setup outbound from wasm as HTTP similar to earlier but is translated into https before going to the internet using envoy [cluster-socket-transport](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-transport-socket)

This can be achieved in istio by using a destination rule along with a service entry for the https endpoint

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name:api
  namespace: apispec:
  hosts:
  - api.com
  exportTo:
  - api
  ports:
  - number: 443
    name: https-port
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: api-destination-rule
  namespace: apispec:
  host: api.com
  trafficPolicy:
    tls:
      mode: SIMPLE
```
