### ISSUE TITLE
Circuit breaking the specific requests

### ISSUE THREAD

**Issue by tahir-ali-uipath** [tetratelabs/proxy-wasm-go-sdk#436]
I am trying to add circuit breaking to specific request. I looked into this example
https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/examples/postpone_requests/main.go but not clear how to add postpone for specific request

```go
func (ctx *httpContext) OnHttpRequestHeaders(numHeaders int, endOfStream bool) types.Action {
	proxywasm.LogInfof("postpone request with contextID=%d", ctx.contextID)
	ctx.pluginCtx.postponed = append(ctx.pluginCtx.postponed, ctx.contextID)
	return types.ActionPause
}
```

## Describe the bug / error
None

## What is your Envoy/Istio version?
```yaml
client version: 1.18.0
control plane version: 1.18.0
data plane version: 1.18.0 (2 proxies)
```

## What is the SDK version?
github.com/tetratelabs/proxy-wasm-go-sdk v0.21.0

## What is your TinyGo version?
tinygo version 0.28.1 darwin/amd64 (using go version go1.20.14 and LLVM version 15.0.0)
